package tui

import (
	"math/rand/v2"
	"time"
)

var afterMidnightGreetings = [50]string{
	"What would you like to explore?",
	"Where would you like to begin?",
	"What can I help you think through?",
	"What's on your mind?",
	"How can I be useful right now?",
	"Want to look into something together?",
	"What would be helpful to discuss?",
	"Is there something you'd like to unpack?",
	"What would you like a hand with?",
	"Shall we take a look at something?",
	"What are you considering?",
	"How may I help?",
	"What would you like to sort out?",
	"Need a calm second perspective?",
	"What can we work through together?",
	"Would you like to ask a question?",
	"What are you curious about?",
	"Is there an idea you'd like to examine?",
	"What would make things clearer?",
	"Want help finding a way forward?",
	"What could use some attention?",
	"Would another perspective help?",
	"What would you like to understand better?",
	"How can I support your thinking?",
	"Is there a decision you'd like to weigh?",
	"What shall we consider?",
	"Want to talk something over?",
	"What would be worth exploring?",
	"Is there something I can clarify?",
	"What would you like to make sense of?",
	"Can I help with a question?",
	"What are you working through?",
	"Would you like help organizing an idea?",
	"What feels worth a closer look?",
	"Is there a topic you'd like to open up?",
	"Where could a little clarity help?",
	"What would you like to reflect on?",
	"Want to untangle something?",
	"What can I help make simpler?",
	"Is there a thought you'd like to develop?",
	"What would be useful to know?",
	"Would you like to compare some options?",
	"What can we quietly work through?",
	"Where should we start?",
	"What would help at the moment?",
	"Is there anything you'd like to investigate?",
	"Want a hand shaping your thoughts?",
	"What question can I help with?",
	"Would you like to reason through something?",
	"What brings you here?",
}

var morningGreetings = [50]string{
	"Good morning. What can I help with?",
	"What would you like to start with?",
	"How can I help you get oriented?",
	"What's first on your list?",
	"What would you like to move forward?",
	"Ready to explore an idea?",
	"What can we figure out together?",
	"How would you like to begin today?",
	"What question shall we start with?",
	"Want to make a plan?",
	"What would help you get started?",
	"Is there a topic you'd like to explore?",
	"What can I help clarify this morning?",
	"Where would you like some direction?",
	"What are you hoping to accomplish?",
	"Shall we work through a question?",
	"What would be a useful first step?",
	"Need help mapping something out?",
	"What idea would you like to develop?",
	"How can I help set things in motion?",
	"What deserves a fresh look?",
	"Would you like to review your options?",
	"What are we looking into today?",
	"Can I help you shape a plan?",
	"What would give you a clear start?",
	"Want to find an answer together?",
	"What should we tackle first?",
	"Where can I help you make progress?",
	"What would you like to learn today?",
	"Is there a choice you'd like to consider?",
	"What can we make clearer?",
	"Would a quick overview help?",
	"What's worth focusing on first?",
	"How can I help with your next step?",
	"What would you like to put in order?",
	"Want to examine a possibility?",
	"What could use a fresh perspective?",
	"Is there something you'd like to plan?",
	"What would make today easier?",
	"Can I help you gather your thoughts?",
	"Where would some context be useful?",
	"What are you ready to look into?",
	"Would you like help setting a direction?",
	"What's a good place for us to begin?",
	"What can I help you prepare?",
	"Shall we turn an idea into a plan?",
	"What would you like to get clear on?",
	"Need help choosing a starting point?",
	"What possibility shall we explore?",
	"How can I assist this morning?",
}

var afternoonGreetings = [50]string{
	"What do you need help with?",
	"What should we focus on?",
	"What's the question?",
	"What would you like to resolve?",
	"Where are you stuck?",
	"What needs a closer look?",
	"How can I help move this along?",
	"What outcome are you aiming for?",
	"Which part should we examine first?",
	"What do you want to know?",
	"Let's work through it. Where do we start?",
	"What needs to be decided?",
	"Can I help narrow the options?",
	"What's the main concern?",
	"What would make this more manageable?",
	"Which details matter most?",
	"What can I help you evaluate?",
	"Need a direct answer or a deeper look?",
	"What's the goal from here?",
	"What should we make sense of?",
	"Where would a second opinion help?",
	"What are the constraints?",
	"What needs to happen next?",
	"Can I help break this down?",
	"What's the key decision?",
	"What would a good result look like?",
	"Which question matters most right now?",
	"What can we simplify?",
	"Need help checking an assumption?",
	"What information are you missing?",
	"Where should we direct our attention?",
	"What would help you choose?",
	"Can I help identify the next step?",
	"What's getting in the way?",
	"What should we compare?",
	"Which angle should we consider?",
	"What would you like to improve?",
	"Need help making a clear case?",
	"What's the problem to solve?",
	"What can we put into perspective?",
	"Where do you need more certainty?",
	"What would make this actionable?",
	"Can I help test your reasoning?",
	"What's the priority?",
	"What should we outline?",
	"Which option needs more thought?",
	"What can I help you complete?",
	"Need help finding the central point?",
	"What are we trying to establish?",
	"What's your next question?",
}

var eveningGreetings = [50]string{
	"Good evening. What would you like to explore?",
	"What would you like to talk through?",
	"How can I help this evening?",
	"Want to take a closer look at something?",
	"What would be useful to consider?",
	"Is there something you'd like help with?",
	"What are you thinking about?",
	"Would you like to explore a few options?",
	"What can we make sense of together?",
	"Where would you like some clarity?",
	"Want to work through an idea?",
	"What would you like another view on?",
	"Is there a question you'd like to discuss?",
	"What can I help you plan?",
	"Would you like to revisit something?",
	"What feels worth discussing?",
	"How can I make this easier?",
	"What would you like to consider next?",
	"Want help weighing the possibilities?",
	"Is there anything you'd like to clarify?",
	"What can we explore at your pace?",
	"Would it help to think this through together?",
	"What would you like to look over?",
	"How can I support you this evening?",
	"Is there an idea you'd like to refine?",
	"What might benefit from a second look?",
	"Want to walk through a question?",
	"What would help bring things into focus?",
	"Is there a plan you'd like to shape?",
	"What can I help put into words?",
	"Would you like to consider another approach?",
	"What would be good to sort through?",
	"How can I help you find perspective?",
	"Is there a subject you'd like to dig into?",
	"What would you like to review together?",
	"Want help connecting a few ideas?",
	"What can we take one step at a time?",
	"Would a thoughtful comparison help?",
	"What would you like to understand tonight?",
	"Is there something you'd like to reconsider?",
	"What can I help you reason about?",
	"Would you like to sketch out some options?",
	"What could use a balanced perspective?",
	"How can I help you find a clear direction?",
	"Is there a question we should examine?",
	"What would you like to discuss first?",
	"Want to explore where an idea leads?",
	"What can I help you bring together?",
	"Would you like to think aloud?",
	"What's worth looking into this evening?",
}

func welcomeGreetings(now time.Time) []string {
	switch hour := now.Hour(); {
	case hour < 6:
		return afterMidnightGreetings[:]
	case hour < 12:
		return morningGreetings[:]
	case hour < 18:
		return afternoonGreetings[:]
	default:
		return eveningGreetings[:]
	}
}

func pickWelcomeGreeting(now time.Time) string {
	greetings := welcomeGreetings(now)
	return greetings[rand.IntN(len(greetings))]
}
